### ISSUE TITLE
Опция открыть папку записи html на диске

### ISSUE THREAD

**Issue by reifwp** [xintrea/mytetra_dev#103]
Уважаемый автор, я вам уже писал, просто напомнить . Чтобы использовать Mytetra совместно с TheBrain, И перетаскивать запись в Myteta в TheBrain .

Вот ,наша переписка

> 

Re: MyTetra v.1.43.x - Пожелания, вопросы, багрепорты
Oleg пишет:
MyTetra 1.44.31
Вроде же была опция, открыть папку с записью на диске? Или я перепутал .
В любом случаи автор, добавьте эту функцию,чтобы по правой кнопке на записе, была функция открыть место записи на локальном диске ..
Ибо я еще собираюсь прикреплять Html записи mytetra к бесплатному TheBrain,там просто в него файл перетаскиваешь любой с компьютера и он заносится как ссылка ..

> Сделать

 это несложно, но... В какой-то момент вам захочется переделать структуру веток или записей. Вы начнете ветки/записи переносить, копировать, удалять. При копировании может измениться каталог. И ваша ссылка будет указывать на несуществующий каталог.<

> предлагаю

 сделать защиту от дурака, кому нужна эта опция,
чтобы по правой кнопки по записи щелкнули и был доступ к записи html файлу на диске, он открылся
Тот пусть включит ее в настройках ..Где-нибудь спрятать под дополнительно спойлер в настройках .А по умолчанию, она отключена .. Очень нужно . Автор.Спасибо ,я надеюсь
2) Автор,скажите а для не программистов, нет инструкции,как пользоваться эксперементальной веткой . А то скачал zip архив,а дальше непонятно ,много папок,а exe файла нет

**Comment by xintrea** [comment]
1) Что-то я подумал, и решил что открытие каталога с записью - это бессмысленная вещь, никакого смысла в прыжках по внутренней структуре базы нет. Когда появляется такая задача, то это значит что пользователь делает что-то нестандартное. Перегружать интерфейс для действий, которые хочет делать пользователь при нестандартном использовании инстумента - это неправильно.

Но могу предложить следующее решение. Скорее всего вы используете Microsoft Windows. Под него есть такая программа как Autohotkey (Автохотки). На ней даже один энтузиаст пилил скрипт TurboTetra. Решение следующее. В MyTetra есть копирование ссылки на запись (в контекстном меню списка записей). Вы можете на Autohotkey написать скрипт, который обнаруживает в буфере обмена ссылку, которая выглядит как такая строка:

`mytetra://note/15421874557wegd0htkv`

Этот скрипт может открыть mytetra.xml, найти запись с id=15421874557wegd0htkv, узнать для нее директорию, и открыть окно проводника с этой директорией. То есть, сделайте все под себя, сторонние инструменты для этого есть.

2) Для непрограммистов лучше экспериментальной веткой не пользоваться. Но если очень хочется, то поставьте Qt+QtCreator (они идут в одном пакете), откройте в нем проект и нажмите "Собрать".

**Comment by reifwp** [comment]
спасибо , буду разбираться

**Comment by reifwp** [comment]
1) Скажите, а если я проще,с помощью опции -Копировать ссылку на запись вида mytetra://note/1536696469apjpk5oubj
Как мне в самой программе mytetra спустя год, имея ссылку
mytetra://note/1536696469apjpk5oubj
найти запись ,ведь поиска по ссылки нет .. Может добавить куда ввести mytetra://note/1536696469apjpk5oubj и мгновенно откроется запись
2) Можно ли внедрить функции,чтобы картинку можно было изменять размер мышкой тянуть стандартно , также перемещать картинку бы мышкой быстро, а не клавиатурой и пробелами как сейчас . Было бы классно быстро изменил ,уменьшил мышкой за край картинку и переместил
3) Автор не хватает, опции история кнопки .. Чтоб не вперед назад , а нажал на кнопку и отобразились 10-15 последних действий ,записей
4) Тоже из этой темы . Ярлыки,закладки 
Добавить кнопку, чтоб выходило окошко где закладки на записи ..Также вариант прятать закладки в папки .. Чтоб больше вошло и тематически
Дело в том, что закладки важны , ибо дерево это одно иерархия вечная по темам . А под текущий конкретный проект нужны записи из разных концов дерева и разных тем .. Внедрите ,автор , это килерфича будет крутая !!
5) Отсюда же вытекают по логике Табы/вкладки как в браузере .

**Comment by reifwp** [comment]
вы может не проверите уже эту тему, поэтому открою новую
