### ISSUE TITLE
No exit on windows

### ISSUE THREAD

**Issue by angerangel** [xintrea/mytetra_dev#108]
Hi,
myTetra process doesn't close on Windows. 
I open MyTetra, I close MyTetra but the process is still open; so if I try to launch again myTetra I get: "Another MyTetra exemplar is running".

**Comment by UUSR** [comment]
Hallo,
where did you get the build of the program, and under what operating system does it work for you?

**Comment by xintrea** [comment]
MyTetra is not close window if click window close button. MyTetra is pull down to systray. See MyTetra icon in systray. May be your DE not have systray? Or systray need for configure for showing MyTetra icon?

For exit from program use File - Quit in menu or push Ctrl+Q.

**Comment by xintrea** [comment]
It is correct behavior. Not a bug.
