### ISSUE TITLE
Увел./уменьш. шрифта текста заметки с помощью сочетания CTRL+ колесико мыши

### ISSUE THREAD

**Issue by ghost** [xintrea/mytetra_dev#119]
Конечно не такая важная фича, но так на будущее может быть / когда-нибудь...
Иногда очень удобно увеличить или уменьшить шрифт текста заметки, как это реализовано в редакторах кода например Qt Creator, Notepad++, CLion  и  в других подобных.

**Comment by xintrea** [comment]
В редакторах Qt Creator, Notepad++, CLion идет работа просто с текстом. Весь текст отображается одним единственным шрифтом, который несложно изменить. В MyTetra же пользователь видит результат рендеринга HTML-разметки.

Тут нужно говорить не о размере шрифта, а о масштабировании области текста. К сожалению, в объекте QTextEdit не предусмотрена такая функциональность, и добавить ее, не меняя саму библиотеку Qt невозможно. Может быть сейчас что-то изменилось, но пару лет назад было именно так.

**Comment by ghost** [comment]
Хорошо, спасибо понял
