### ISSUE TITLE
Мультивыделение текста в заметке с помощью CTRL

### ISSUE THREAD

**Issue by ghost** [xintrea/mytetra_dev#123]
Реализуемо ли, мультивыделение с помощью клавиши CTRL и мыши?

Например выделить в тексте заметки сразу несколько слов не стоящих рядом друг с другом и сделать жирным или поменять цвет или шрифт, т. е. выделять слова или несколько слов с помощью кнопки мыши с зажатой клавишей CTRL.

На данные момент выделяю слово с зажатой CTRL перехожу к выделению другого слова, с первого слова выделение исчезает.

**Comment by xintrea** [comment]
Нет, такое поведение реализовываться не будет. Сейчас много других важных нерешенных проблем, кроме того с помощью Ctrl+клик происходит переход по ссылке, если слово является ссылкой. Как обрабатывать такую ситуацию вместе с вашим функцоналом - непонятно.
