### ISSUE TITLE
Не применяется к тексту шрифт

### ISSUE THREAD

**Issue by ghost** [xintrea/mytetra_dev#132]
Mytetra Версия 1.44.79
OS Xubuntu 18.04
Размер шрифта меняется, а сам шрифт не меняется.

Возможно проблема у меня или где-то настройки надо изменить, не могу понять в чем причина, раньше менялся без проблем.

https://yadi.sk/i/rNwL3vJNufgSoQ

**Comment by xintrea** [comment]
Это похоже на регрессию в Qt.

Вот тут обсуждение: https://www.linux.org.ru/forum/development/15435316?cid=15442864

Кратко: разломали применение шрифта в Qt 5.13.0 и более новых.

Поэтому надо устанавливать Qt 5.12.6, в ней все будет работать.

**Comment by retmas** [comment]
Данный [баг](https://bugreports.qt.io/browse/QTBUG-80475) обещают починить в 5.14.1.
А пока предлагаю workaround:
_app/src/libraries/wyedit/EditorTextArea.cpp:
void EditorTextArea::onChangeFontFamily(QString fontFamily) : 646:_
```
// QTBUG-80475 workaround
#if (QT_VERSION < QT_VERSION_CHECK(5, 13, 0)) // || (QT_VERSION > QT_VERSION_CHECK(5, 14, 0))
    format.setFontFamily(fontFamily);
#else
    format.setFontFamilies(QStringList{fontFamily});
#endif
```
Проверял в 5.12.4 и 5.14.0
Если нужно, могу сделать PR
