### ISSUE TITLE
кнопка showText - малый размер открепляемого окна

### ISSUE THREAD

**Issue by VicDobrov** [xintrea/mytetra_dev#136]
Проблема: **диалог открепляемого окна ничем не отличается от диалогов настройки**, диалога прогресса поиска и т.п.
**Геометрию открепляемого окна сложно запомнить в оконных менеджерах** (например для kwin), т.к. нет уникальных признаков (класс или ключевая фраза в заголовке)

Способ решения 1: Добавить в заголовок открепляемого окна после названия Заметки фразу о её откреплении, например:
жмём кнопку showText на заметке с именем: «Текущие записи», открывается диалог с таким заголовком окна: «Текущие записи - deallocation», или «**Текущие записи - Отдельное окно**»

Способ решения 2: изменить класс диалога вместо mytetra на «mytetra deallocation» или «mytetra unfastening»

Способ решения 3: запоминать геометрию открепляемого окна в самой программе mytetra…

**Comment by xintrea** [comment]
> Способ решения 3: запоминать геометрию открепляемого окна в самой программе mytetra…

Я буду делать именно этот способ. Но вот не знаю когда запилю.

**Comment by VicDobrov** [comment]
Я хочу добавить к заголовку открепляемого окна текст: «Моя заметка» **- Отдельное окно**.
Можете подсказать, в каком месте кода можно добавить к имени заметки Дополнительный текст: **- Отдельное окно** ???

Ждать вариант 3 очень долго! И некоторые менеджеры окон могут игнорировать геометрию окон или переопределять её…

**Comment by xintrea** [comment]
Вариант 3 реализован. Завершающий коммит в этой серии доработок был следующий:

https://github.com/xintrea/mytetra_dev/commit/3522147998a2c5056f4736991211fffcec5c8c3f
