### ISSUE TITLE
Приложение не выходит по Quit, остается в правом нижнем углу

### ISSUE THREAD

**Issue by ghost** [xintrea/mytetra_dev#140]
Закрываю приложение, оно сворачивается в правый нижний угол, нажимаю правой кнопкой в меню Quit, происходит синхронизация а иконка так и остается там, то есть можно опять запустить кликнув по ней.
OS Xubuntu 18.04, версия mytetra 1.44.112

**Comment by xintrea** [comment]
Хм, странно. Я это исправил для Linux, но под MacOs не проверял. Ранее была проблема выхода, если при этом в фоне крутилась синхронизация. Скажите, у вас галка "Синхронизировать при выходе из MyTetra" стоит?

**Comment by ghost** [comment]
> Хм, странно. Я это исправил для Linux, но под MacOs не проверял. Ранее была проблема выхода, если при этом в фоне крутилась синхронизация. Скажите, у вас галка "Синхронизировать при выходе из MyTetra" стоит?

У меня Linux Xubuntu. Раньше проблем не было, я недавно сборку собрал. Кстати насчет синхронизации при выходе - убрал галку приложение стало закрываться, но это конечно не очень удобно, потому что можешь забыть провести синхронизацию.

**Comment by xintrea** [comment]
> Закрываю приложение, оно сворачивается в правый нижний угол, нажимаю правой кнопкой в меню Quit, происходит синхронизация а иконка так и остается там, то есть можно опять запустить кликнув по ней.
OS Xubuntu 18.04, версия mytetra 1.44.112

Я вас изначально неправильно понял. Вы написали "можно опять запустить кликнув по ней". На самом деле, это значит, что MyTetra, в случае если стоит галка "Синхронизировать при выходе", при нажатии "Выход" делает синхронизацию, но в конце синхронизации не выходит, а продолжает работать. Получается, что если стоит галка "Синхронизировать при выходе", то выйти из программы штатным образом вообще невозможно.

Сейчас я повторил вашу проблему, я ее исправлю. Проблема возникла из-за сильной переделки подсистемы синхронизации в последних коммитах.

**Comment by VicDobrov** [comment]
Уточню: Если включена синхронизация при выходе, то выход из mytetra не происходит:
Ctrl+Q закрывает в трей вместо выхода. 
После этого надо кликнуть на значок в трее и закрыть окно. Тогда прога закроется…

my system: Arch Linux, mytetra 1.44.114

**Comment by xintrea** [comment]
Исправлено в коммите 277016c1babe50f0ca5be17bd6e88a7de1bc30b0
