### ISSUE TITLE
Ошибочный статус синхронизации

### ISSUE THREAD

**Issue by Shura0** [xintrea/mytetra_dev#141]
Версия 1.44.31.lin_64

Настроена синхронизция через git и раздражает вот такое поведение:
![изображение](https://user-images.githubusercontent.com/2156669/87516297-d681c400-c685-11ea-94fa-9032d9455333.png)

В чём ошибка? Ведь всё синхронизировалось нормально.

**Comment by xintrea** [comment]
Попробуйте эти же команды выполнить последовательно в консоли. Возможно, там Git ругается на какую-нибудь неустановленную настроечную переменную и просит ее ввести. А упрощенный терминал, который вы видите в окне синхронизации, не показыват запросов ввода.

**Comment by Shura0** [comment]
В консоли показывает всё тоже самое, но дальше ещё идут строки, что всё засинхронизировано.

Я нашёл, в чём основная причина, в команде
git commit -a -m "home commit"
Mytetra пытается выполнить команду без кавычек и всё съезжает. Заменил комментарий на "home" и всё заработало.

**Comment by xintrea** [comment]
Правильно, ведь полная команда выглядит так:

sh -c "cd /home/shura/ ... "

И вы в кавычки добавляете еще кавычки.
