### ISSUE TITLE
Не как не могу собрать mytetra

### ISSUE THREAD

**Issue by ZOGC** [xintrea/mytetra_dev#142]
Здравствуйте,

хочу собрать mytetra с поддержкой горячих клавишь - такую я только в исходных кодах нашел

на linux.org.ru нашел что оказывается она собирается так

cmake mytetra.run
make
make install

в исходниках описания этого нет - видимо все и так вкурсе (кроме меня)

собрать я её собрал но как это всё дело собрать в кучу со всеми библиотеками? чтоб была тогоже вида что доступна в бинарном виде на сайте 1.44.31 версии (там нет горячих клавишь потому и хочу собрать новее)

**Comment by xintrea** [comment]
Не знаю, что вы нашли на LORе, но mytetra - это Qt-only проект, и собирается он, соответственно, командами:

qmake mytetra.pro
make
make install

Для последней версии из исходников потребуется Qt 5.11.x и выше.

**Comment by ZOGC** [comment]
> Не знаю, что вы нашли на LORе, но mytetra - это Qt-only проект, и собирается он, соответственно, командами:
> 
> qmake mytetra.pro
> make
> make install
> 
> Для последней версии из исходников потребуется Qt 5.11.x и выше.

Здравствуйте, спасибо за ответ

ошибся 
cmake mytetra.pro конечно

cобирается у меня нормально без проблем - проблема в переносимости

после сборки имеется

$ ls bin -l
total 47649
-rwxr-xr-x 1 root root 48635496 Jul 13 21:45 mytetra

$ ls app/bin -l
total 8077
-rw-r--r-- 1 root root  124148 Jul 13 22:02 icons.qrc
-rwxr-xr-x 1 root root 1704368 Jul 13 22:06 mimetex
-rwxr-xr-x 1 root root 6195840 Jul 13 22:06 mytetra
-rw-r--r-- 1 root root    6831 Jul 13 22:02 mytetra.qrc
drwxr-xr-x 7 root root       7 Jul 13 22:02 resource

на той ОС где производилась сборка всё работает но если перенести на другую ОС (на флешку скинуть и с другой ОС попробовать запустить) то требует кучу библиотек - а вот собранная mytetra с вашего сайта работает везде - собственно хочется такуюже но с поддержкой горячих клавиш:)

**Comment by xintrea** [comment]
> ошибся
> cmake mytetra.pro конечно

qmake, если быть точным.


> на той ОС где производилась сборка всё работает но если перенести на другую ОС (на флешку скинуть и с другой ОС попробовать запустить) то требует кучу библиотек - а вот собранная mytetra с вашего сайта работает везде - собственно хочется такуюже но с поддержкой горячих клавиш

Тогда разбирайтесь как делать переносимые программы в Qt, или ждите очередного релиза, я для релизов традиционно собираю переносимые бинарные сборки.

**Comment by ZOGC** [comment]
понял спасибо

думал это както само делается во время сборки - просто я чегото не знаю
