### ISSUE TITLE
Где находится последняя версия программы для Windows?

### ISSUE THREAD

**Issue by it19862** [xintrea/mytetra_dev#145]
Где находится последняя версия программы для Windows?

Я плохо разбираюсь в GIT.
Если я правильно понимаю, то последняя версия программы находится здесь - [v.1.44.139](https://github.com/xintrea/mytetra_dev/releases/tag/v.1.44.139).
Но я так понимаю, что её там нет..

**Используется.**
 - win 7x64

**Comment by xintrea** [comment]
MyTetra - это кроссплатформенная программа. Код один и тот же что под Windows что под Linux.

Видимо, вас интересует готовая сборка под Windows.

Готовая сборка под Windows лежит на официальной странице программы: 
https://webhamster.ru/site/page/index/articles/projectcode/105

Там лежит сборка стабильной версии 1.44.31. Более новых официальных стабильных сборок не выпускалось, так как сейчас стабильной версии еще нет. Если хотите заполучить новую нестабильную версию, ее нужно самостоятельно собирать из исходников (открыть проект в QtCreator, нажать Build).

**Comment by it19862** [comment]
@xintrea 
Хотелось бы попробовать 1.44.139. 
У меня нет QtCreator. 
Не хотелось бы возиться с установкой QtCreator.

Может у вас есть возможность собрать проект?

**Comment by xintrea** [comment]
> @xintrea
> Хотелось бы попробовать 1.44.139.
> У меня нет QtCreator.
> Не хотелось бы возиться с установкой QtCreator.
> Может у вас есть возможность собрать проект?

Совсем забыл, на официальном форуме есть раздел "Сборки энтузиастов", там более новые версии MyTetra народ выкладывает: https://webhamster.ru/punbb/viewtopic.php?id=198

Там есть версия 1.44.139 под Windows.

**Comment by danfe** [comment]
> Более новых официальных стабильных сборок не выпускалось, так как сейчас стабильной версии еще нет.

At the end of 2023, the latest version on the website is still 1.43.27 (July 2018), while the latest tag here on GitHub is 1.44.160 (January 2021).  What are current plans towards next official stable version?  Should downstream packagers use 1.43.27 or better switch to 1.44.160?

**Comment by xintrea** [comment]
Better switch to last version in experimental branch.

**Comment by danfe** [comment]
> Better switch to last version in experimental branch.

Fetching the latest commit might work for someone building locally, but distro packages usually try to follow something more stable, e.g. official release or at least a tag.  Among the latest ten tags, eight were done in 2018, two in 2020, and remaining one in the early 2021.  With the latest commit eab60ad being over a year old now, perhaps it's time to tag it?

**Comment by xintrea** [comment]
> Fetching the latest commit might work for someone building locally, but distro packages usually try to follow something more stable, e.g. official release or at least a tag. Among the latest ten tags, eight were done in 2018, two in 2020, and remaining one in the early 2021. With the latest commit [eab60ad](https://github.com/xintrea/mytetra_dev/commit/eab60ade77275191eaa257da138b9f3985235e91) being over a year old now, perhaps it's time to tag it?

Yes, eab60ad is the latest official commit on the experimental branch.
How do you suggest tagging?

**Comment by danfe** [comment]
> How do you suggest tagging?

IDK, it depends on how you pick the minor version number.  The latest tag from 25.01.2021 is v.1.44.**160** so I guess the new tag should be v.1.44.**160+n** where **n** is some positive integer.

**Comment by danfe** [comment]
Thanks a lot for tagging [v.1.44.183](https://github.com/xintrea/mytetra_dev/releases/tag/v.1.44.183), much appreciated!
