### ISSUE TITLE
Проблемы с UTF-8?

### ISSUE THREAD

**Issue by bvn13** [xintrea/mytetra_dev#146]
Текст заметок в какой кодировке хранится и помещается в буфер обмена?

Имею негативный кейс. Написал заметку, пытаюсь скопировать текст в Jira от Attlasian в описание задачи. И при сохранении получаю от Jira ошибку на неверный символ для кодировки  UTF-8. Отсюда возникло позодрение, что в myTetra заметки хранятся не в UTF-8

**Comment by bvn13** [comment]
Воспользовался декодером Лебедева. Попытался автоматически декодировать заметку в УТФ.
Получил преобразование ISO-8859-1 -> UTF-8

Заметки хранятся в непонятной кодировке ISO-8859-1 ?

**Comment by xintrea** [comment]
> Текст заметок в какой кодировке хранится и помещается в буфер обмена?
В буфер обмена текст помещается в системной кодировке.

> Написал заметку, пытаюсь скопировать текст в Jira от Attlasian в описание задачи. И при сохранении получаю от Jira ошибку на неверный символ для кодировки UTF-8. Отсюда возникло позодрение, что в myTetra заметки хранятся не в UTF-8
Вы не написали ни версию операционной системы, ни версию MyTetra, ни откуда взяты бинарники MyTetra (официальный релиз, сборка энтузиастов, самостоятельная сборка). Но вообще в MyTetra заметки хранятся в HTML-файлах, и кодировка у них UTF-8, вне зависимости от операционной системы.

Некоторые сайты, такие как Stack Owerflow, по неизвестным причинам подмешивают даже в англоязычный текст различные нестандартные символы. От этого куча проблем: например при сохранении текста с такого сайта, текст сохранится только до такого нестандартного символа, а все после него будет отброшено. Пользователь может даже не заметить этого, пока не вернется к записи и не промотает ее да проблемного места. Поведение базового класса QTextEdit при обработке нестандартных символов неопределено. Поэтому если у вас текст был запомнен в MyTetra из какого-то странного места, например из Java-приложения, в котором использовалась дикая кодировка, или из кривого PDF, то не удивляйтесь, что текст в MyTetra содержит странную разметку и нестандартные символы.

**Comment by bvn13** [comment]
Текст я вводил вручную. 
OS Fedora 32 Linux, XOrg, i3wm

**Comment by xintrea** [comment]
Если системная локаль UTF-8, то все, включая буфер обмена, должно работать в UTF-8. В MyTetra никаких специальных преобразований для UTF-8 не производится. UTF-8 - это базовая внутренняя кодировка любого Йе-приложения.

Возможно, вы вводили какие-то спецсимволы? Попробуйте это сделать напрямую в Jira, возможно и тогда сохранение такого текста будет сопровождаться предупреждением об ошибочном символе.

**Comment by xintrea** [comment]
Да, и еще вы не написали версию MyTetra и что у вас за сборка.
