### ISSUE TITLE
Где смотреть список изменений?

### ISSUE THREAD

**Issue by ixvz** [xintrea/mytetra_dev#147]
Поставил 160 версию - и вообще не вижу отличий от 139 - может быть там чтото интересное есть... а я даже не вижу

**Comment by xintrea** [comment]
Наверно, надо смотреть историю коммитов? Там все на русском.

https://github.com/xintrea/mytetra_dev/commits/experimental

В твоем случае надо смотреть все что было сделано после Nov 26, 2020.

**Comment by xintrea** [comment]
В любом случае, сейчас доработки делаются в другой ветке:

https://github.com/xintrea/mytetra_dev/commits/basesManagement

Это разрабатывается встроенный менеджер баз данных, чтобы можно было легко переключаться между разными базами. И чтобы снять вопросы пользователей "А где лежит база данных MyTetra?", "А почему я удалил и снова поставил MyTetra, а она открывает старую базу данных?".

**Comment by ixvz** [comment]
кстати да было бы неплохо

мне вот удобнее на несколько (на 2) баз было бы разбить.
