### ISSUE TITLE
В зашифрованных нодах не шифруются изображения

### ISSUE THREAD

**Issue by nikto-b** [xintrea/mytetra_dev#148]
Шифруется только текст, при этом можно спокойно смотреть на изображения  
Так и должно быть или что-то не так?

**Comment by xintrea** [comment]
Да, никто не обещал шифрацию картинок. Только текст и аттачи. Связано это с тем, что стандартный QTextEdit не позволяет вмешиваться в процесс получения картинки с диска и по интернет-ссылке чтобы расшифровать ее на ходу. Когда в QTextEdit появится такой мнханизм, тогда можно будет сделать шифрацию.

**Comment by nikto-b** [comment]
> Да, никто не обещал шифрацию картинок. Только текст и аттачи. Связано это с тем, что стандартный QTextEdit не позволяет вмешиваться в процесс получения картинки с диска и по интернет-ссылке чтобы расшифровать ее на ходу. Когда в QTextEdit появится такой мнханизм, тогда можно будет сделать шифрацию.

Т.е. проблема в том чтобы отобразить в редакторе расшифрованную картинку, я верно понял?
А если, пока это не реализовано, создавать временную директорию на диске (обычно есть tmp что чистится при выключении. В маке должно быть. В винде вроде как тоже что-то такое было), расшифровывать туда и отображать оттуда?

**Comment by xintrea** [comment]
Это получится дырой в безопасности: человек будет уверен, что у него картинки зашифрованы. Но в момент работы с записью придется держать директорию, в которой будут лежать расшифрованные картинки. Нетрудно написать скрипт/вирус, который тупо смотрит в данную директорию и вытаскивает оттуда картинки.
