### ISSUE TITLE
Tools->Preferences-> любая опция - окно на весь экран. Cancel/Ok не доступны

### ISSUE THREAD

**Issue by geniot** [xintrea/mytetra_dev#149]
При выборе Tools->Preferences-><любая опция> открывается диалог на весь экран. Размер этого окна нельзя изменить. Кнопки Cancel/Ok внизу диалога труднодоступны (через tab-пробел или перетягивание окна чуть-чуть вверх). 
Qt 5.15.2
MyTetra v.1.44.160

**Comment by xintrea** [comment]
Вы пробуете собрать экспериментальную версию, которая была переключена в режим Android-приложения. В файле app.pro надо выставить:

TARGET_OS=ANY_OS

Или выкачайте более свежие изменения.

**Comment by geniot** [comment]
Спасибо, помогло. Я использовал исходники из тэга v.1.44.160, как бы предполагая, что это последний стабильный релиз.
