### ISSUE TITLE
Не отображается иконка в System Tray, если не использовать sudo

### ISSUE THREAD

**Issue by geniot** [xintrea/mytetra_dev#151]
v.1.44.147
Диструбутив LXLE 64Bit 18.04.3
ui: LXDE
При запуске из командной строки 
$ sudo mytetra
иконка в System Tray (xpanel) появляется. 

При запуске 
$ mytetra
или через кнопки в меню - нет. 
Т.е. без прав root иконка в system tray не отображается.

Я попробовал 
sudo chown vitaly.vitaly /home/vitaly/.config/mytetra/ -R
sudo chmod 777 /home/vitaly/.config/mytetra/ -R
Не помогает. Видимо, чего-то ещё не хватает.
Проверил что System Tray в принципе работает (создал тестовое приложение на Java. Дополнительных прав для запуска  не потребовалось.)

Action log пустой. 

Примечательно также, что при таких же настройках на ноутбуке всё работает. Но там я сразу всё установил. А на desktop'е пришлось повозиться (удалить старый Qt, удалить экспериментальную установку mytetra).

**Comment by xintrea** [comment]
> Примечательно также, что при таких же настройках на ноутбуке всё работает. 

Видимо, дело в правах. Проверьте, что на все файлы MyTetra установлены права на чтение/запись для вашего текущего пользователя. Работайте от обычного пользователя, а не от суперпользователя. 

Включите логирование в консоль - Настройки - Разное (Misc) - Выводить отладочные сообщения в консоль, возможно так вы увидите сообщение о проблеме с систреем.

Посмотрите в системные логи (не в логи MyTetra), возможно там будет сообщение о недоступности систрея.

**Comment by PavelSann** [comment]
Возможна проблема связана с этим #155

**Comment by geniot** [comment]
Я попробовал скопировать иконку в /usr/share/icons/ и ~/.local/share/icons/
Не помогло.

**Comment by PavelSann** [comment]
Там нужно ещё код поправить и собрать. Иконку копирует и сама программа при установке.

27 апреля 2021 г. 4:25:21 GMT+05:00, geniot ***@***.***> пишет:
>Я попробовал скопировать иконку в /usr/share/icons/ и
>~/.local/share/icons/
>Не помогло.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/xintrea/mytetra_dev/issues/151#issuecomment-827204410

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by xintrea** [comment]
> Иконку копирует и сама программа при установке.

А запускается ли процедура установки, если MyTetra запускается как переносимое приложение?
