### ISSUE TITLE
1_44_160_win32: Windows 10: Как расшарить записи с коллегами?

### ISSUE THREAD

**Issue by edwardsmirnov** [xintrea/mytetra_dev#153]
Как расшарить с разными коллегами разные подветки, но так, чтобы пароли тоже были разные?

**Comment by xintrea** [comment]
Такого функционала никогда не предусматривалось. MyTetra - это клссический PIM-менеджер. Буква "P" означает Personal. Коль менеджер персональный, то и пароль один для одного человека.
