### ISSUE TITLE
Не работают HTML спойлеры - которых очень сильно не хватает в mytetra 

### ISSUE THREAD

**Issue by ixvz** [xintrea/mytetra_dev#158]
вот такое например 

`<details open>скрытое/показанное содержимое</details>`

если в код HTML в mytetra добавить - не работает... я так понимаю это от движка QT както зависит
в будущем стоит рассчитывать что появятся спойлеры? 

версия 165

**Comment by xintrea** [comment]
Это зависит от развития Qt-шного класса QTextEdit, который является и редактором и рендером HTML. Я не видел желаний поддерживать спойлеры и тег `<details>`. 

Можете написать в багзиллу на qt.io, чтобы QTextEdit начал поддерживать данный функционал.
