### ISSUE TITLE
How strikethrough text?

### ISSUE THREAD

**Issue by MGuerrera** [xintrea/mytetra_dev#163]
Is there the possibility of selecting text and converting it to strikethrough text?

**Comment by fftmp** [comment]
Yes, use 'strike out' button (with icon ~~S~~) in editor or ctrl + shift + s.

**Comment by MGuerrera** [comment]
I have 1.43.27 version of MyTetra for Linux.
No strike symbol on my gui.
Ctrl + shift + s hasn't any effect on selected text.

![image](https://github.com/xintrea/mytetra_dev/assets/15629810/177e9018-fe8a-4885-bbf9-d1a67f7ed960)

**Comment by xintrea** [comment]
> I have 1.43.27 version of MyTetra for Linux.

It's very old version. 

Try selfbuild from experimental branch, or get build 1.44.165 from entusiast: https://webhamster.ru/punbb/viewtopic.php?id=198

Newest version have strikeout button, it added in toolbar config window in editor setup.

**Comment by MGuerrera** [comment]
Solved, thank you.
