### ISSUE TITLE
Диалоговое окно при запуске программы

### ISSUE THREAD

**Issue by itspec-ru** [xintrea/mytetra_dev#19]
При каждом запуске mytetra появляется окно с полем ввода и кнопкой Cancel, заголовок "mytetra".
Окно внешне похоже на то, что для ввода пароля, но без текста-подсказки. Поле ввода при этом заблокировано (нет возможности туда что либо писать).

Исходники из "experimental"
Система Gentoo Linux
qt-5.5.1
gcc-4.9.3

**Comment by xintrea** [comment]
У меня такое не наблюдается. Чтобы понять, что присходит, мне нужна копия conf.ini.

**Comment by itspec-ru** [comment]
ссылка на conf.ini:
https://yadi.sk/i/7HPlSWbHqpRhB
скриншот окна
https://yadi.sk/i/9H_wH7pYqpV9x

раньше (использовал для сборки qt4) такого не наблюдалось.
С какого-то  момента с qt4 собираться перестало, перешёл на qt5 и появилось это окно при запуске.

**Comment by antongus** [comment]
Подтверждаю. Сегодня пересобрал свежую версию, диалог всё ещё появляется.
Qt5.6.0, gcc 4.8.4, mint 17.3. Диалог появляется примерно через две секунды после появления главного окна. Удалил ~/config/.mytetra, - то же самое.
![mytetra-annoying-dialog](https://cloud.githubusercontent.com/assets/6680984/17268628/9ddf09d0-5651-11e6-96f9-c1879aed5adf.png)

**Comment by xintrea** [comment]
@antongus  @itspec-ru
Блин, у меня такое не повторяется. Прошу запустить последнюю сборку из experimental, дождаться окна, нажать cancel и выйти из программы. Мне нужно увидеть консольный лог.

**Comment by itspec-ru** [comment]
Имеем: Gentoo Linux, gcc (Gentoo 5.3.0 p1.1, pie-0.6.5) 5.3.0, qt-5.6.1
Собрал из experimental v.1.32.329.

Вот собственно весь консольный вывод;
WalkHistory::clear()
Set main program file to  "mytetra"
Debug message before set message handler for target OS:  "any"
Set alternative handler myMessageOutput() for debug message
19:35:14 [INI] Debug message after set message handler
19:35:14 [INI] Check full current path  "/home/itspec"
19:35:14 [INI] Check config file  "/home/itspec/conf.ini"
19:35:14 [INI] Detect home directory  "/home/itspec/.mytetra"
19:35:14 [INI] Check config file  "/home/itspec/.mytetra/conf.ini"
19:35:14 [INI] File conf.ini can't' find in home directory  "/home/itspec/.mytetra"
19:35:14 [INI] Try find conf.ini in home subdirectory  "/home/itspec/.config/mytetra"
19:35:14 [INI] Check config file  "/home/itspec/.config/mytetra/conf.ini"
19:35:14 [INI] Config file  "/home/itspec/.config/mytetra/conf.ini"  is exists
19:35:14 [INI] Short config file name  "conf.ini"
19:35:14 [INI] Config directory name  "/home/itspec/.config/mytetra"
19:35:14 [INI] Config init file success find in home subdirectory  "/home/itspec/.config/mytetra"
19:35:14 [INI] Set work directory to  "/home/itspec/.config/mytetra"
19:35:14 [DBG] In iconsCollectionCheck(). Mytetra XML dir is:  "./data"
19:35:14 [DBG] Icons directory is exist
19:35:14 [DBG] Stylesheet success loaded from "/home/itspec/.config/mytetra/stylesheet.css"
19:35:14 [DBG] Get interface language "ru"
19:35:14 [DBG] Use language file  ":/resource/translations/mytetra_ru.qm"
19:35:14 [DBG] Column count change. New column count:  3
19:35:14 [DBG] RecordTableView::init()
19:35:14 [DBG] Show event of find dialog
19:35:15 [DBG] Init random generator
19:35:15 [DBG] MainWindow::restoreTreePosition() :  ("0", "1457971448osauk0q9jl")
19:35:15 [DBG] MainWindow::saveTextarea() : id : ""
19:35:15 [DBG] Save textarea...
19:35:15 [DBG] WalkHistory::add() : id  ""
19:35:15 [DBG] WalkHistory::add() : mode  0
19:35:15 [DBG] WalkHistory::add() start status:
19:35:15 [DBG] In RecordTableView setTableData() start
19:35:15 [DBG] MetaEditor::clearAll()
19:35:15 [DBG] Set new AttachTableModel to NULL data
19:35:15 [DBG] In table select non present
19:35:15 [DBG] In RecordTableView set new model stop
19:35:15 [DBG] Restore session succesfull
19:35:15 [DBG] WalkHistory::clear()
19:35:15 [DBG] In timer PeriodicSyncro working method
19:35:15 [DBG] MainWindow::saveTextarea() : id : ""
19:35:15 [DBG] Save textarea...
19:35:15 [DBG] WalkHistory::add() : id  ""
19:35:15 [DBG] WalkHistory::add() : mode  0
19:35:15 [DBG] WalkHistory::add() start status:
19:35:15 [DBG] AppConfig::set_tree_position() :  ("0", "1457971448osauk0q9jl")
19:35:15 [DBG] Run shell "sh -c"
19:35:15 [DBG] Run command "cd /home/itspec/.config/mytetra/data ; git add . ; git commit -a -m MyTetraCommit; git pull -s recursive ; git push"
19:35:15 [DBG] Process started
19:35:15 [DBG] [Console]  "На ветке master\n"
19:35:15 [DBG] [Console]  "Ваша ветка обновлена в соответствии с «origin/master».\n"
19:35:15 [DBG] [Console]  "нечего коммитить, нет изменений в рабочем каталоге\n"
19:35:18 [DBG] [Console]  "Already up-to-date.\n"
19:35:18 [DBG] MainWindow::onFocusChanged() to  ""
19:35:20 [DBG] MainWindow::onFocusChanged() to  ""
19:35:21 [DBG] [Console]  "Everything up-to-date\n"
19:35:21 [DBG] Close process, PID 0
19:35:21 [WRN] QIODevice::read (QProcess): device not open
19:35:21 [DBG] Process stop
19:35:21 [DBG] Reload XML data if last data not found
19:35:21 [DBG] MainWindow::restoreTreePosition() :  ("0", "1457971448osauk0q9jl")
19:35:21 [DBG] MainWindow::saveTextarea() : id : ""
19:35:21 [DBG] Save textarea...
19:35:21 [DBG] WalkHistory::add() : id  ""
19:35:21 [DBG] WalkHistory::add() : mode  0
19:35:21 [DBG] WalkHistory::add() start status:
19:35:21 [DBG] In RecordTableView setTableData() start
19:35:21 [DBG] MetaEditor::clearAll()
19:35:21 [DBG] Set new AttachTableModel to NULL data
19:35:21 [DBG] In table select non present
19:35:21 [DBG] In RecordTableView set new model stop
19:35:21 [DBG] Start timer with delay:  300  ID:  22

**Comment by xintrea** [comment]
Благодарю, посмотрим

**Comment by xintrea** [comment]
@itspec-ru

У меня просьба: переименуйте бинарник mytetra на mytetra01 и запустите. Что пишется в заголовке этого странного окна?

**Comment by xintrea** [comment]
@itspec-ru
> Собрал из experimental v.1.32.329

Да, и еще, нужно содержимое вашего conf.ini для v.1.32.329

**Comment by itspec-ru** [comment]
Удалил каталог ~/.config/mytetra. При запуске тоже самое окно.

Переименовал /usr/bin/mytetra в /usr/bin/mytetra01
В заголовке окна mytetra01

Мой конфиг (вероятно стандартный) без каких-либы изменений в настройках:

[General]
actionLogMaximumSize=1
addnewrecord_expand_info=1
attachAppendDir=
attachSaveAsDir=
autoClosePasswordDelay=10
autoClosePasswordEnable=false
checkBasePeriod=20
customDateTimeFormat=
cutbranchconfirm=true
editorCursorPosition=0
editorScrollBarPosition=0
enableCreateEmptyRecord=false
enableCustomDateTimeFormat=false
enableDecryptFileToTrashDirectory=false
enableLogging=false
enablePeriodicCheckBase=false
enablePeriodicCheckMessage=false
enablePeriodicSyncro=false
enableRecordWithAttachHighlight=true
findInBaseExpand=true
findScreenTreeSearchArea=0
findscreen_find_inauthor=true
findscreen_find_inname=true
findscreen_find_intags=true
findscreen_find_intext=false
findscreen_find_inurl=false
findscreen_howextract=1
findscreen_show=true
findscreen_wordregard=1
findsplitter_size_list="712,219"
focusWidget=
hideEditorTools=
howpassrequest=atClickOnCryptBranch
hspl_size_list="351,921"
iconCurrentSectionName=Essential
interfaceMode=desktop
interfacelanguage=en
mainwingeometry="0,22,1276,976"
passwordMiddleHash=
passwordSaveFlag=false
periodicSyncroPeriod=300
previewIconSize=24
printdebugmessages=true
programm=mytetra
recordTableFieldsWidth="256,632"
recordTableShowFields="name,tags"
recordTableShowHorizontalHeaders=true
recordTableShowVerticalHeaders=false
recordWithAttachHighlightColor=#d1e3c5
recordtableSelectedRecordId=
rememberCursorAtHistoryNavigation=true
rememberCursorAtOrdinarySelection=true
runinminimizedwindow=false
showSplashScreen=false
synchrocommand=
synchroonexit=false
synchroonstartup=false
syncroConsoleDetails=false
tetradir=./data
trashdir=./trash
trashmaxfilecount=200
trashsize=5
tree_position="0,1300000000aaaaaaaaa1"
uglyQssReplaceHeightForTableView=0
version=34
vspl_size_list="248,460"

**Comment by itspec-ru** [comment]
На всякий случай выкладываю консольный вывод для начальной конфигурации, для conf.ini предыдущего поста

WalkHistory::clear()
Set main program file to  "/usr/bin/mytetra01"
Debug message before set message handler for target OS:  "any"
Set alternative handler myMessageOutput() for debug message
19:39:39 [INI] Debug message after set message handler
19:39:39 [INI] Check full current path  "/usr/bin"
19:39:39 [INI] Check config file  "/usr/bin/conf.ini"
19:39:39 [INI] Detect home directory  "/home/itspec/.mytetra"
19:39:39 [INI] Check config file  "/home/itspec/.mytetra/conf.ini"
19:39:39 [INI] File conf.ini can't' find in home directory  "/home/itspec/.mytetra"
19:39:39 [INI] Try find conf.ini in home subdirectory  "/home/itspec/.config/mytetra"
19:39:39 [INI] Check config file  "/home/itspec/.config/mytetra/conf.ini"
19:39:39 [INI] Config file  "/home/itspec/.config/mytetra/conf.ini"  is exists
19:39:39 [INI] Short config file name  "conf.ini"
19:39:39 [INI] Config directory name  "/home/itspec/.config/mytetra"
19:39:39 [INI] Config init file success find in home subdirectory  "/home/itspec/.config/mytetra"
19:39:39 [INI] Set work directory to  "/home/itspec/.config/mytetra"
19:39:39 [DBG] In iconsCollectionCheck(). Mytetra XML dir is:  "./data"
19:39:39 [DBG] Icons directory is exist
19:39:39 [DBG] Stylesheet success loaded from "/home/itspec/.config/mytetra/stylesheet.css"
19:39:39 [DBG] Get interface language "en"
19:39:39 [DBG] Use language file  ":/resource/translations/mytetra_en.qm"
19:39:39 [DBG] Column count change. New column count:  2
19:39:39 [DBG] RecordTableView::init()
19:39:39 [DBG] Show event of find dialog
19:39:40 [DBG] Init random generator
19:39:40 [DBG] Textarea geometry X Y  0   74
19:39:40 [DBG] Textarea geometry Width Height  593   17
19:39:40 [DBG] Textarea frame geometry Width Height  593   17
19:39:40 [DBG] Textarea geometry X Y  0   74
19:39:40 [DBG] Textarea geometry Width Height  890   17
19:39:40 [DBG] Textarea frame geometry Width Height  890   17
19:39:40 [DBG] Textarea geometry X Y  0   74
19:39:40 [DBG] Textarea geometry Width Height  921   17
19:39:40 [DBG] Textarea frame geometry Width Height  921   17
19:39:40 [DBG] MainWindow::restoreTreePosition() :  ("0", "1300000000aaaaaaaaa1")
19:39:40 [DBG] MainWindow::saveTextarea() : id : ""
19:39:40 [DBG] Save textarea...
19:39:40 [DBG] WalkHistory::add() : id  ""
19:39:40 [DBG] WalkHistory::add() : mode  0
19:39:40 [DBG] WalkHistory::add() start status:
19:39:40 [DBG] In RecordTableView setTableData() start
19:39:40 [DBG] MetaEditor::clearAll()
19:39:40 [DBG] Set new AttachTableModel to NULL data
19:39:40 [DBG] In table select non present
19:39:40 [DBG] In RecordTableView set new model stop
19:39:40 [DBG] Restore session succesfull
19:39:40 [DBG] WalkHistory::clear()
19:39:40 [DBG] MainWindow::onFocusChanged() to  "knowTreeView"
19:39:43 [DBG] Main window focus deactivate, save all state.
19:39:43 [DBG] MainWindow::saveTextarea() : id : ""
19:39:43 [DBG] Save textarea...
19:39:43 [DBG] WalkHistory::add() : id  ""
19:39:43 [DBG] WalkHistory::add() : mode  0
19:39:43 [DBG] WalkHistory::add() start status:
19:39:43 [DBG] Save window geometry and splitter sizes
19:39:43 [DBG] Save new main window geometry
19:39:43 [DBG] Config set find splitter list to  (712, 219)
19:39:43 [DBG] AppConfig::set_tree_position() :  ("0", "1300000000aaaaaaaaa1")
19:39:43 [DBG] MainWindow::onFocusChanged() to  ""
19:39:43 [DBG] MainWindow::onFocusChanged() to  "knowTreeView"
19:39:44 [DBG] Main window focus deactivate, save all state.
19:39:44 [DBG] MainWindow::saveTextarea() : id : ""
19:39:44 [DBG] Save textarea...
19:39:44 [DBG] WalkHistory::add() : id  ""
19:39:44 [DBG] WalkHistory::add() : mode  0
19:39:44 [DBG] WalkHistory::add() start status:
19:39:44 [DBG] Save window geometry and splitter sizes
19:39:44 [DBG] Save new main window geometry
19:39:44 [DBG] Config set find splitter list to  (712, 219)
19:39:44 [DBG] AppConfig::set_tree_position() :  ("0", "1300000000aaaaaaaaa1")
19:39:44 [DBG] MainWindow::onFocusChanged() to  ""
19:39:44 [DBG] MainWindow::onFocusChanged() to  "knowTreeView"
19:39:48 [DBG] MainWindow::saveTextarea() : id : ""
19:39:48 [DBG] Save textarea...
19:39:48 [DBG] WalkHistory::add() : id  ""
19:39:48 [DBG] WalkHistory::add() : mode  0
19:39:48 [DBG] WalkHistory::add() start status:
19:39:48 [DBG] Save window geometry and splitter sizes
19:39:48 [DBG] Save new main window geometry
19:39:48 [DBG] Config set find splitter list to  (712, 219)
19:39:48 [DBG] AppConfig::set_tree_position() :  ("0", "1300000000aaaaaaaaa1")
19:39:48 [DBG] Main window focus deactivate, save all state.
19:39:48 [DBG] MainWindow::saveTextarea() : id : ""
19:39:48 [DBG] Save textarea...
19:39:48 [DBG] WalkHistory::add() : id  ""
19:39:48 [DBG] WalkHistory::add() : mode  0
19:39:48 [DBG] WalkHistory::add() start status:
19:39:48 [DBG] Save window geometry and splitter sizes
19:39:48 [DBG] Save new main window geometry
19:39:48 [DBG] Config set find splitter list to  (712, 219)
19:39:48 [DBG] AppConfig::set_tree_position() :  ("0", "1300000000aaaaaaaaa1")
19:39:48 [DBG] MainWindow::saveTextarea() : id : ""
19:39:48 [DBG] Save textarea...
19:39:48 [DBG] WalkHistory::add() : id  ""
19:39:48 [DBG] WalkHistory::add() : mode  0
19:39:48 [DBG] WalkHistory::add() start status:
19:39:48 [DBG] Save window geometry and splitter sizes
19:39:48 [DBG] Save new main window geometry
19:39:48 [DBG] Config set find splitter list to  (712, 219)
19:39:48 [DBG] AppConfig::set_tree_position() :  ("0", "1300000000aaaaaaaaa1")
19:39:48 [DBG] Save editor config file
19:39:48 [DBG] Save database config file
19:39:48 [DBG] Save mytetra config file


Start MyTetra v.1.32.329

**Comment by xintrea** [comment]
@antongus @itspec-ru 
Какая битность у ваших линухов?

**Comment by antongus** [comment]
У меня ubuntu 16.04 x86_64. Голый openbox, без DE.

**Comment by itspec-ru** [comment]
Использую mytetra дома и на работе, синхронизирую git'ом.
Дома gentoo linux 32-разрядная
На работе gentoo linux x86_64
На обоих машинах при запуске появляется диалог.

**Comment by antongus** [comment]
Подумал, что можно сделать `git bisect`, и найти коммит, в котором проблема появилась. Для этого надо было найти коммит "хороший", без этой проблемы. Так вот, я не смог найти хороший коммит! Я откатился аж до коммита 3c70dfd3af1f4de50c19e7848f7a5e4872a02c19  от января 2014 года. И в этом коммите точно так же выскакивает окошко. Дальше откатываться не получилось, потому что предыдущий коммит уже не комилируется под Qt5.

Видимо, ошибка пришла с повышением версии Qt, на старых версиях она не проявлялась.
У меня сейчас Qt 5.6.0. Какой версией Qt я компилировал раньше, когда у меня получалась версия без выскакивающего окошка - я не помню.  (@xintrea, думаю, что раз у вас ошибка не воспроизводится, то у вас, вероятно, более старая версия Qt?).

**Comment by itspec-ru** [comment]
По поводу версии qt я уже здесь писал (мой второй коментарий). Да, именно после перехода на qt5 появилась проблема, а сборка mytetra под qt4 на моей системе сломалась.

**Comment by antongus** [comment]
Я раньше собирал какой-то версией Qt5 (кажется 5.4.0). То есть, проблема возникла не при переходе Qt4-Qt5, а при повышении версии Qt5.

**Comment by itspec-ru** [comment]
Если память не изменяет, первая установленная мной версия qt5 была 5.5.0. И как я уже писал, при версии qt-5.5.1 проблема уже точно была. Сейчас у меня qt-5.6.1

**Comment by xintrea** [comment]
Я сейчас разворачиваю виртуалку, чтобы на Минте 17.3 попробовать. Но буду смотреть 32-х битную версию, потому что у меня на работе и дома только 32-х битные хостовые системы. Если бага не будет, то возможно это проблемы 64-х битной версии. Но на такую отладку уйдет больше времени, потому что мне даже отладиться негде.

**Comment by xintrea** [comment]
Ага, itspec-ru пишет, что на 32-х битах проблема тоже есть. Ну вот попробую на Минте. К сожалению, Генту я вообще не знаю.

**Comment by xintrea** [comment]
> Видимо, ошибка пришла с повышением версии Qt, на старых версиях она не проявлялась.
У меня сейчас Qt 5.6.0. Какой версией Qt я компилировал раньше, когда у меня получалась версия без выскакивающего окошка - я не помню. (@xintrea, думаю, что раз у вас ошибка не воспроизводится, то у вас, вероятно, более старая версия Qt?).

@antongus, да, я наконец то внимательно прочитал ваше размышление, и похоже что вы правы. У меня более старый Qt 5.4.2, видимо поэтому я ошибки не вижу. Я щас в виртуалку скачиваю 5.6.0 32 bit, буду смотреть что там.

**Comment by xintrea** [comment]
@antongus, в общем, все верно. Проблема в Qt 5.6.0. Окно увидел в 32-х битной сборке в Windows 7. Буду разбираться.

**Comment by xintrea** [comment]
@antongus @itspec-ru 

https://www.linux.org.ru/forum/development/12976081?lastmod=1477653145292#comment-12976736

Последний мердж решает вашу проблему. Баг в Qt 5.5, перешел в 5.6.x

https://github.com/xintrea/mytetra_dev/commit/bdbd5430e28d8056d7493bacfd1a26a267aa4935

**Comment by antongus** [comment]
Шикарно, спасибо!

**Comment by itspec-ru** [comment]
Спасибо!
