### ISSUE TITLE
Ошибка при синхронизации

### ISSUE THREAD

**Issue by itspec-ru** [xintrea/mytetra_dev#20]
Версия 1.32.250

В дереве навигации создаю подветку третьего (именно третьего) уровня
например так
-test1
 --------test2 [1]
-----------------------test3 [2]

подветки содержат записи.
выделяю любую запись в последней подветке и жму Синхронизация
Получаю диалоговое окно с ошибкой и программа закрывается.
RecordTableData::getField() : get unavailable record index 0
Program was closed.
При этом в окне синхронизации видим Everything up-to-date, что говорит об успешной синхронизации

Если выделять запись не последней подветки, а любую другую (независимо от уровня) то всё проходит без ошибок.
Опытным путём установил, что ошибка возникает на третьем уровне вложенности (на втором всё нормально).

**Comment by xintrea** [comment]
Я знаю, эта регрессия появилась на этой неделе, щас разбираюсь.

**Comment by xintrea** [comment]
http://webhamster.ru/site/page/index/main/news/358

**Comment by xintrea** [comment]
Прошу потестировать версию 1.32.251

https://github.com/xintrea/mytetra_dev/commit/887e1b56b522999d5bdc99ffd1ad3d62c2d9ba19

**Comment by itspec-ru** [comment]
v.1.32.251
потестировал немного,
похоже проблема решена.
Спасибо!
