### ISSUE TITLE
невозможно удалить значёк для ветки/подветки

### ISSUE THREAD

**Issue by itspec-ru** [xintrea/mytetra_dev#21]
После того как для ветки/подветки установлен значёк (иконка), нет возвожности отменить это действие.
Кроме этого, при назначении иконки утрачивается возможность визуализации признака зашифрованности (значёк замка замещается). Может быть стоит как-то выделить название зашифрованной ветки, например другим цветом.

**Comment by xintrea** [comment]
Да, сейчас стоит две задачи:

1. Если есть действие "добавить иконку", значит должно быть действие "удалить иконку". Оно пока не реализовано.

2. Я подумывал у зашифрованных веток (у которых назначена иконка) поверх иконки,в углу справа вверху, рисовать маленький значек замочка. Еще вариант, как вы предложили, цветом букв или цветом фона. 

Проблема варианта с маленьким замочком - замочек будет очень маленьким, примерно 5-7 пикселей по ширине/высоте, и он может сливаться с иконкой или мешать иконке.

Вариант с маленьким квадратиком вместо замочка (например 4x4) - те же что и у предыдущего пункта, только менее выраженные.

Вариант с цветом букв - дальтоники не смогут пользоваться.

Вариант с цветом фона - надписи в дереве становятся визуально "полосками", выглядит отвратно.

Пока не решил какой вариант выбрать. Если есть еще идеи, или знаете как логично обосновать выбор варианта, отписывайтесь здесь.

**Comment by itspec-ru** [comment]
Ещё вариант - выделять подчёркиванием, но тоже - не очень

**Comment by xintrea** [comment]
Удаление иконки реализовано:

https://github.com/xintrea/mytetra_dev/commit/5e8d6c5c982284f9f1d32e039f9ab3cf0a2116d6
