### ISSUE TITLE
Don't automatically restart program after config changes!

### ISSUE THREAD

**Issue by Punkoivan** [xintrea/mytetra_dev#26]
When I change preferences, program close with message:
"The program will have to be restarted for changes to take effect."
Please, ask user WHEN restart program - automatically and immediately or later and manually.

**Comment by xintrea** [comment]
Later and manually.

I don't know crossplatform mechanism for self-restart application.

**Comment by alexivanou** [comment]
[http://www.cyberforum.ru/qt/thread608036.html](http://www.cyberforum.ru/qt/thread608036.html)

**Comment by xintrea** [comment]
> http://www.cyberforum.ru/qt/thread608036.html

Это обсуждение про обычный запуск программы из другой программы. У нас же  используется объект QtSingleApplication, который запрещает запуск второго экземпляра программы.

Даже если программа запустит сама себя и сразу выйдет, новый экземпляр не запустится, так как в нем сработает блокировка на запуск, так как все равно будет момент, когда первый экземпляр еще не завершил работу.

**Comment by alexivanou** [comment]
Это с позиции "как оно получается, используя SingleApplication".
Варианта 2 - либо перейти по уровню выше и запитаться от простого Application, либо сделать отдельный лаунчер, который мониторит лок-файл и ждёт пока тот пропадёт. Разумеется ждет разумное время, потом форсит перезапуск. И из SingleApplication вызывать этот лаунчер и завершать работу.
Есть еще третий вариант - подправить SingleApplication так, чтобы лок-файлы он создавал, привязывая имя файла к id процесса. Тогда повторный запуск не сможет найти лок-файл и позволит запуститься. Но это бьет логику. А по моему опыту логика первична. На логичный алгоритм можно легко довесить сотню костылей, а на сотню костылей логичный алгоритм повесить увы.

**Comment by xintrea** [comment]
Перезапуск программы происходит настолько редко, что эта доделка не актуальна.

**Comment by retmas** [comment]
> I don't know crossplatform mechanism for self-restart application.

[How to make an Application restartable](https://wiki.qt.io/How_to_make_an_Application_restartable)
Идея вполне подойдет и для вашего QtSingleApplication

**Comment by xintrea** [comment]
Благодарю, посмотрю на досуге

**Comment by xintrea** [comment]
Посмотрел, там на самом деле не происходит перезапуска программы. Там просто происходит повторный запуск объекта QApplication после его разрушения если был флаг перезапуска. Но помимо объекта программы есть куча других объектов - изменяемые и неизменямые конфигурационные данные, временные и постоянные объекты различных типов, и все это не входит в реализацию QApplication. Другими словами, QApplication - важный, но не единственный объект в программе на одном и том же контексте выполнения. Указанное решение этого всего не учитывает. Либо программа должна была изначально писаться так, чтобы все перечисленные объекты были принудительно включены в класс QApplication.

**Comment by retmas** [comment]
> Посмотрел, там на самом деле не происходит перезапуска программы.

Конечно. Экземпляр процесса, как объекта ядра, сам себя перезапустить не может, т.к. некому будет его запустить, когда он завершится. Ссылка выше - подсказка на будущее, идея, если решитесь когда-нибудь на глубокий рефакторинг. Этот момент, я уверен, рано или поздно станет насущным. И лучше рано, чем поздно) Но это (необходимость перелопатить весь код и т.п.) - вещь для отдельной темы.

**Comment by retmas** [comment]
Кстати, честно говоря я не понял, почему вы сделали принудительное завершение процесса при применении изменении настроек программы. Это не ожидаемое поведение для пользователя (и первый пост это только подтверждает). Программа должна сама перезапуститься, либо предоставить перезапуск пользователю. Предоставить перезапуск пользователю же означает, что он **сам** выйдет из программы и потом запустит.

**Comment by xintrea** [comment]
> Предоставить перезапуск пользователю же означает, что он сам выйдет из программы и потом запустит.

В окне настроек есть два типа параметров: "простые" и "сложные". Если пользователь изменил "простой" параметр, то программа не потребует перезапуска, с для "сложного" потребуется перезапуск. "Простых" параметров подавляющее большинство.

Если пользователь изменил "сложный" параметр, то нормальная работа программы с таким измененным параметром без перезапуска будет невозможна. Поэтому пользователю и не дается возможности самому выйти из программы, ведь пока он не вышел, он может сделать действие, которое вкупе с измененным "сложным" параметром приведет к совершенно непредсказуемому результату. Поэтому появляется предупреждающее сообщение и только одна кнопка ОК, после нажатия которой, в случае наличия кроссплатформенного метода перезагрузки программы, должна по хорошему происходить перезагрузка.
