### ISSUE TITLE
Moving tree

### ISSUE THREAD

**Issue by Punkoivan** [xintrea/mytetra_dev#34]
Hello!
is there any way to moving trees between trees?

For example:

```
parent tree1 - |
                     | - sibling tree
                     |
                     | - sibling tree 2
parent tree2-|
                     |
                     | - sibling tree 3

parent tree3 ( ex-sibling tree 3 with all notes)
```
                      
I want to change parent tree for sibling tree (sibling tree 3 move to parent tree 1) and make sibling tree parents tree.

**Comment by alexivanou** [comment]
Yes. You can right-click on 'sibling tree 3' and do 'Cut item'. Then on any parent tree right-click and do 'Past item'. You can paste trees many times and at any other nodes.

**Comment by Punkoivan** [comment]
Nice! Thanks!
