### ISSUE TITLE
[bug] Windows is not maximized after reopen from tray

### ISSUE THREAD

**Issue by AndreyMZ** [xintrea/mytetra_dev#37]
#### Configuration
Windows 7 x86_64.
MyTetra v.1.42.2

#### Steps
1. Start MyTetra.
2. Resize the window somehow but do not maximize.
3. Maximize the window.
4. Close (X) the window.
5. Reopen the windows from the system tray.

#### Actual result
The window is NOT maximized.

#### Expected result
The window is maximized.

http://webhamster.ru/site/page/index/articles/projectcode/105
> **Главные особенности программы**
> - Всегда запоминается геометрия окна

**Comment by PavelSann** [comment]
Пока обсуждается.
https://github.com/ExIngus/mytetra_dev/commit/a94d8d6057a832a3258bdeb7de4d710f5058154d#commitcomment-20167260

**Comment by PavelSann** [comment]
https://github.com/xintrea/mytetra_dev/pull/46
