### ISSUE TITLE
[bug] Window is not maximized after program restart

### ISSUE THREAD

**Issue by AndreyMZ** [xintrea/mytetra_dev#38]
#### Configuration
Windows 7 x86_64.
MyTetra v.1.42.2

#### Steps
1. Start MyTetra.
2. Resize the window somehow but do not maximize.
3. Maximize the window.
4. Quit from the program (e.g. Ctrl+Q).
5. Start MyTetra.

#### Actual result
The window is NOT maximized. And it is a little bigger that the size of desktop.

#### Expected result
The window is maximized.

http://webhamster.ru/site/page/index/articles/projectcode/105
> **Главные особенности программы**
> - Всегда запоминается геометрия окна

**Comment by xintrea** [comment]
Баг не воспроизводится. Закрыто по причине неактуальности.
