### ISSUE TITLE
1.30 on linux: error while loading shared libraries: libQtSvg.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by retorquere** [xintrea/mytetra_dev#4]
I run ubuntu 15.04, and I can't find a package that installs libqtsvg

**Comment by xintrea** [comment]
In older Ubuntu releses user install package libqt4-svg.

Try install libqt4-svg.

**Comment by xintrea** [comment]
But i recomendet not use release 1.30. Its wery old release with pair bugs. Try build from "experimental" branch.
