### ISSUE TITLE
Не коректная вставка некоторых изображений из буфера обмена.

### ISSUE THREAD

**Issue by PavelSann** [xintrea/mytetra_dev#41]
Win7 x64.
При вставке некоторых png картинок с прозрачным фоном из буфера обмена появляются артефакты.
При вставке по ссылке проблем нет.

Например эта картинка https://hsto.org/files/5cc/363/d97/5cc363d97a434cb0bc775cf76969c00c.png
при вставке через буфер обмена выглядит так
http://img.techpowerup.org/161223/capture031-20161223-215612.png
при вставке по ссылке так
http://img.techpowerup.org/161223/capture032-20161223-215932.png

**Comment by xintrea** [comment]
Да, есть такая проблема, но решения ее нет, пока не изменят сам движок отображения прозрачных картинок в Qt. Проблема касается PNG с прозрачностью и GIF с прозрачностью.

Пока могу только предложить открывать примитивный графический редактор типа MSPaint/KolorPaint, потом Ctrl+V, Ctrl+A, Ctrl+C.
