### ISSUE TITLE
Отсутствует иконка в трее

### ISSUE THREAD

**Issue by Lexofein** [xintrea/mytetra_dev#42]
https://pp.vk.me/c637728/v637728112/297d1/d7PnfemQdME.jpg
kde plasma + arch

**Comment by xintrea** [comment]
Предлагаю в этой проблеме разобраться любителям плазмы и арча.

**Comment by Lexofein** [comment]
Интересный подход. С учетом того что mytetra единственное из всех приложений которое имеет проблемы с иконкой в трее, сразу напрашивается вывод - проблема в кде, арче и всех остальных нормально отображающих иконки в трее приложениях.

**Comment by xintrea** [comment]
Вы не поняли. В MyTetra используется стандартный механизм Qt по отображению иконки в трее. Если он не работает в вашей конфигурации, то придется разбираться самостоятельно. У меня нет ни времени ни возможности.

Для начала можете самостоятельно собрать программу из исходников на своей платформе и посмотреть как будет себя вести иконка в трее, возможно она появится. Можете попробовать отключить плазму и посмотреть что будет, возможо тоже иконка появится. Если иконки ни так ни так не появится, надо посмотреть отладочный вывод (включив дебаг в *.pro файле), возможно в нем будет сообщение о проблеме.

**Comment by Lexofein** [comment]
Да не. Извините что время потратил. Косяк действительно не в вас, не в кде и не в арче, а в человеке который пакет собирал.
Когда не из репозитория, а у вас напрямую скачал - иконка появилась. Так что еще раз приношу извинения за то что зря подумал, но вы тоже поймите - когда все приложения показывают иконки, а одно нет - на кого тут подумаешь еще =)
