### ISSUE TITLE
Что делают эти кнопки?

### ISSUE THREAD

**Issue by strowk** [xintrea/mytetra_dev#51]
Не хватает всплывающих описаний иконок в менюшках. Нет возможности только по картинке понять что делает кнопка с паутинкой или кнопка с ёлкой, а особо желания нажимать на кнопки без понимания, что они делают тоже нет - вдруг она стирает целиком всю запись или ещё что-нибудь в таком духе делает. Открывать документацию ради этих кнопок можно, но не хочется. Дружелюбные интерфейсы прикрепляют к кнопкам всплывающие подсказки (hint) с подробным описанием зачем эта кнопка тут находится и что делает.

**Comment by xintrea** [comment]
Пояснения появляются внизу окна прграммы в строке состояния. В следующих версиях планируется дублировать эти описания на всплывающие подсказки. Опция будет отключаемой.
