### ISSUE TITLE
Текст без шрифта

### ISSUE THREAD

**Issue by strowk** [xintrea/mytetra_dev#52]
По умолчанию не отображается никакого шрифта в том месте, где выбирается шрифт. Очевидно, что набираемый текст какому-то шрифту соответствует, раз уж он отображается, но шрифта нет. Более того, если часть текста выделить и шрифт "поменять" на Arial, то мы увидим, что текст не изменится (вероятно шрифт по умолчанию - Arial), но у него теперь и впредь будет отображаться шрифт Arial, а вот у остального текста - так и останется безымянный одиночка.

**Comment by xintrea** [comment]
Да, я знаю об этой проблеме. В тексте действительно есть шрифт по-умолчанию, о котором стандартный объект редактора не сообщает при запросе из другого места кода. Считается, что текст не имеет форматирования, если он отформатирован стандартным шрифтом. Дело осложняется тем, что эти параметры шрифта платформозависимы, и, похоже, что еще зависят от настроек среды. С этим надо отдельно разбираться.

**Comment by xintrea** [comment]
В ветке 1.44.x эта проблема исправлена, шрифт всегда отображается.
