### ISSUE TITLE
Вставка форматированного текста игнорируя формат

### ISSUE THREAD

**Issue by strowk** [xintrea/mytetra_dev#57]
Вставка форматированного текста должна иметь возможность делать это, игнорируя форматирование (применяя то, которое уже в заметке используется).

**Comment by xintrea** [comment]
Я подумаю над этим. Сейчас реализавана обратная задача: вставка текста с форматированием, и потом очистка текста кнопками [C] или [TXT].

**Comment by dinitrol** [comment]
О, Да! Очень этого не хватает. Привык что почти во всех программах можно вставлять не форматированный текст кнопками Ctrl+Shift+V. А здесь приходиться сначала вставлять текст, потом его выделять и нажимать кнопку TXT. Но все равно MyTetra лучшая программа :)

**Comment by EnochTheWise** [comment]
Доброго, меня наоборот оттолкнула эта фича "вставка отформатированного" текста.
Обычно мне нужно "быстро вставить что-то там из консоли" и тут возникают проблемы(консоли нынче ASCII -цветастые) в итоге тратится масса времени на чистку от ненужных html тэгов. А если с сайта то ууууу... 8(((
Как мне видится хватило бы просто markdown/wiki разметки в режиме - "своими лапами".
Пока думаю оформить FR...
ЗЫ Кстати очень удобны контролы и редактор у TinyMCE, хотя это скорее привычка, на всех форумах оно присутствует.

**Comment by dinitrol** [comment]
@EnochTheWise, вы наверное нас не поняли. Мы как раз и хотим чтобы форматированный текст из буфера обмена вставлялся без форматирования.

**Comment by dinitrol** [comment]
Ctrl+V - вставка форматированного текста с цветом, размером, и так далее (это уже есть в MyTetra).
Ctrl+Shift+V - вставка очищенного от форматирования текста, применяя то, что уже используется в документе (вот этого не хватает в MyTetra).

**Comment by EnochTheWise** [comment]
> вы наверное нас не поняли

Я немного не так выразился, для меня очень неудобно что по умолчанию вставка с форматированием(обычно copy&paste&save, красоту потом наведем), ну и второе пожелание это упростить форматирование(md/wiki) которое достаточно просто делается руками.
Не стал почему-то оформлять отдельной темой, хотя так было бы удобнее наверное. 8)
