### ISSUE TITLE
Исправление файла mytetra.run

### ISSUE THREAD

**Issue by xintrea** [xintrea/mytetra_dev#58]
От pipitos: 

(http://webhamster.ru/punbb/viewtopic.php?pid=1589#p1589)

В текущей версии для Linux 64 для запуска есть файл "mytetra.run" который не работает если запускать его из любого каталога кроме текущего с программой. Это вызывает сложности если делать"ярлык" на рабочем столе.
Чтобы избавиться от проблемы я привел его к такому виду:
#!/bin/sh

PROGDIR=$(dirname $0)

LD_LIBRARY_PATH=$PROGDIR/lib:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

$PROGDIR/mytetra

Возможно не плохо будет сделать что-то подобное в дистрибутиве.

**Comment by retmas** [comment]
Я раньше для себя модифицировал его так:
```
#!/bin/sh

appdir=`dirname $0`
apppath=`(cd "$appdir"; /bin/pwd)`
LD_LIBRARY_PATH="$apppath"/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH
$apppath/mytetra
```
чтобы корректно получить полный путь

**Comment by xintrea** [comment]
Хорошо, я это учту в следующих релизах.
