### ISSUE TITLE
HotKeys

### ISSUE THREAD

**Issue by mcold** [xintrea/mytetra_dev#60]
ИМХО основная проблема программы связана с трудоемкостью заведения новых записей (по сравнению с аналогами). Одним из методов является введение быстрых клавиш или хотя бы подбор по первым буквам меню через Alt (но для этого все операции необходимо завести все операции в меню программы). Очень большая просьба добавить быстрые клавиши для работы с деревом и записью

**Comment by xintrea** [comment]
Настройка горячих клавиш планируется в будущих версиях.

**Comment by xintrea** [comment]
Сделано в v.1.44.55, ждите релиза.
