### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by mcold** [xintrea/mytetra_dev#61]
При переносе записи падает ошибка getItem() + полный краш приложения
![1](https://cloud.githubusercontent.com/assets/13967667/25037653/fe6f6e08-2102-11e7-99b5-d68d1ec0c452.jpg)
![2](https://cloud.githubusercontent.com/assets/13967667/25037656/03026876-2103-11e7-9f62-9b6864a91380.jpg)

**Comment by xintrea** [comment]
Нужна дополнительная информация:

- Операционная система?
- Десктоп окружение (в случае Linux)?
- Откуда взяли дистрибутив программы? Брали готовый с оф.сайта webhamster.ru, собирали вручную, ставили из репозитария?

Также нужна информация о действиях, которые привели к этой ошибке. Вам нужно нащупать последовательность действий, которые гарантированно приводят к этой ошибке, и сообщить их.

**Comment by mcold** [comment]
OS Windows 10 x64
Брал дистрибутив с оф.сайта webhamster.ru
Порядок действий:
1) раскрываем ветку
2) из корневой папки переносим запись в папку предка
[подробности](https://yadi.sk/d/azaeb1bw3GzmhW)

**Comment by xintrea** [comment]
К сожалению, у меня баг не повторяется.
У вас он всегда срабатывает при переносе записи в директорию на уровень вверх?
Вы можете мне прислать базу, и указать запись, на которой происходит сбой?

**Comment by mcold** [comment]
увы (а может и к лучшему) у меня тоже

**Comment by xintrea** [comment]
В некоторых графических средах был такой баг Qt: выбирается запись из списка для перетаскивания, и с зажатой клавишей мышки курсор двигается не влево к ветке дерева, а вверх или вниз, а только потом к ветке. И тогда выбиралась не захваченная запись, а соседняя, над которой протащили курсор.

Я вижу, что у вас выбиралась самая верхняя/нижняя запись. Может быть, вы схватили запись, протащили курсор вверх, где небыло записи, а потом перетянули на нужную ветку. Или наоборот, схватили нижнюю и потянули сначала вниз. И из-за этого захватилась "пустая" запись, и произошёл сегфолт. Пожалуйста, проверьте такой сценарий.

**Comment by mcold** [comment]
Пробовал перетаскивать записи в пустые места, ошибка не повторяется
