### ISSUE TITLE
Кнопка ОК по умолчанию в окне создания записи

### ISSUE THREAD

**Issue by pkeeper** [xintrea/mytetra_dev#62]
Мелочь, но было бы приятно.

В окне создания записи, если стоит настройка о возможности создания пустых записей,
написав название записи и нажав **Enter** окно записи закрывается так как по умолчанию фокус стоит на кнопке **Cancel** (кстати она так же и называется в русской локали).
Нужно чтобы фокус по умолчанию был на **ОК**
Так можно быстро создавать записи (например список дел).

Конечно работает **CTRL+Enter**.. но все же эту комбинацию нужно знать чтобы пользоватся ею.

Использую v.1.42.2 под Linux

**Comment by xintrea** [comment]
Вы что-то путаете. При написании названия записи, фокус будет на поле
ввода названия записи. Поэтому и сделано Ctrl+Enter.

12.05.2017, Artem melanich<notifications@github.com> написал(а):
> Мелочь, но было бы приятно.
>
> В окне создания записи, если стоит настройка о возможности создания пустых
> записей,
> написав название записи и нажав **Enter** окно записи закрывается так как по
> умолчанию фокус стоит на кнопке **Cancel** (кстати она так же и называется в
> русской локали).
> Нужно чтобы фокус по умолчанию был на **ОК**
> Так можно быстро создавать записи (например список дел).
>
> Конечно работает **CTRL+Enter**.. но все же эту комбинацию нужно знать чтобы
> пользоватся ею.
>
> Использую v.1.42.2 под Linux
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/xintrea/mytetra_dev/issues/62


-- 
Со всяческими пожеланиями, Сергей.
http://webhamster.ru

**Comment by pkeeper** [comment]
Да, фокус будет на поле ввода, это текстовый фокус (мигающий курсор).. 
А фокус кнопки по умолчанию которая нажмется при нажатии Enter в любых полях формы (кроме текстового где это значит перевод строки) будет на кнопке Cancel.. это видно по слегка более жирному начертанию кнопки. 
То есть если написать текст в поле названия и нажать Enter (а не CTRL+Enter) то нажмется кнопка по умолчанию которая в даном случае Cancel и форма закроется без сохранения.

Я не уверен как это устроено на том чем вы пишите но в свое время на Делфи можно было указать кнопку по умолчанию а если не указано оно таковой считало первую создавшуюся кнопку, возможно тут тоже самое, первой была создана Cancel, и нужно просто установить свойство вроде **default** для кнопки ОК
![mytetra_issue](https://cloud.githubusercontent.com/assets/851405/26053350/2d29bfc4-3971-11e7-9498-09257ef5c5b0.png)

**Comment by xintrea** [comment]
Видимо, это зависит от операционки и среды. У меня везде ОК по умолчанию:

![add](https://cloud.githubusercontent.com/assets/769826/26057886/1b3aa0fe-3984-11e7-9e41-93ad89815059.png)

**Comment by pkeeper** [comment]
Вот о такой галочке я говорил ![mytetra_issue](https://i.stack.imgur.com/k0gNZ.png)

Как попало инициализируются кнопки скорее всего потомучто не выставленна вручную главная кнопка.
Больше деталей [тут](https://stackoverflow.com/questions/11887938/how-to-make-a-qpushbutton-pressable-for-enter-key), возможно поможет

**Comment by xintrea** [comment]
Исправлено в коммите:

https://github.com/xintrea/mytetra_dev/commit/0e67a04d782e784fe73846e0c84fe8015f35b90a
