### ISSUE TITLE
Обновление адреса репозитория anatolean

### ISSUE THREAD

**Issue by anatolean** [xintrea/mytetra_dev#63]
Добрый день.
Обновите, пожалуйста, ссылку на мою базу **Anatolean**.
Новая ссылка: http://webhamster.ru/mytetrashare/index/http:~~raw.github.com~anatolean~mytetra~master~mytetra.xml

Большое спасибо!

**Comment by xintrea** [comment]
Заменил.

16.05.2017, Anatoly<notifications@github.com> написал(а):
> Добрый день.
> Обновите, пожалуйста, ссылку на мою базу **Anatolean**.
> Новая ссылка:
> http://webhamster.ru/mytetrashare/index/http:~~raw.github.com~anatolean~mytetra~master~mytetra.xml
>
> Большое спасибо!
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/xintrea/mytetra_dev/issues/63


-- 
Со всяческими пожеланиями, Сергей.
http://webhamster.ru
