### ISSUE TITLE
Не добавляются файлы без расширений

### ISSUE THREAD

**Issue by Alexilmarranen** [xintrea/mytetra_dev#64]
Файлы без расширений в при прикреплении к записи добавляются с нулевым размером. При удалении такого файла возникает ошибка "Не могу удалить файл file_name на диске. Файл не существует." Версия 1.42.2 для Linux.

**Comment by xintrea** [comment]
Да, проблема есть. Посмотрим.

**Comment by PavelSann** [comment]
Похоже причина та же
https://github.com/xintrea/mytetra_dev/pull/48

**Comment by xintrea** [comment]
Исправлено в коммите:

https://github.com/xintrea/mytetra_dev/commit/7c7eb12795bc6bd78bb72bdcca1fa422f006a13c
