### ISSUE TITLE
Работа со ссылками

### ISSUE THREAD

**Issue by Alexilmarranen** [xintrea/mytetra_dev#65]
В контекстном меню записи есть пункт "Скопировать ссылку". Как этой ссылкой можно пользоваться? Так как очень хотелось бы иметь возможность ссылаться в одной записи на другую в этой же (или другой, когда станет доступна работа с несколькими) базе. При попытке написать конфиг обработчика ссылок для KDE (~/.kde/share/services/mytetra.protocol) столкнулся с двумя проблемами. Обработка ссылки невозможна, т.к. непонятно с каким ключом передать бинарнику mytetra ссылку. Даже если ключ существует, а я его просто не знаю, то видимо возникнет еще проблема с количеством запущенных экземпляров mytertra - судя по ответному сообщению более одного экземпляра не запускается, соответственно и обработка ссылки не произойдет.

**Comment by xintrea** [comment]
> хотелось бы иметь возможность ссылаться в одной записи на другую

Именно для этого ссылки на запись и сделаны. Вот здесь обучалка, все подробно разжёвано:

https://youtu.be/cOYKPfVesFc?t=947
