### ISSUE TITLE
Увеличенные элементы интерфейса при использовании Qt 5.7.1

### ISSUE THREAD

**Issue by Alexilmarranen** [xintrea/mytetra_dev#66]
При использовании Qt версии 5.7.1 на Debian 9 все элементы интерфейса стали заметно больше. Есть ли какой-то способ регулировать масштабирование интерфейса?

**Comment by Alexilmarranen** [comment]
Частично проблема решается при помощи stylesheet.css (padding для QToolButton) и параметра uglyQssReplaceHeightForTableView в файле настроек. Но по-прежнему несоразмерными являются элементы дерева QTreeView, элементы выбора начертания и размера шрифта в редакторе и т. п.

**Comment by xintrea** [comment]
Попробуйте Qt5 Configuration Tool

https://www.linux.org.ru/news/opensource/12636830
https://sourceforge.net/projects/qt5ct/

Писал какой-то наркоман, как ей пользоваться я так и непонял. Но некоторым это удается.

**Comment by Alexilmarranen** [comment]
Qt5 Configuration Tool вещь действительно странная. Попробовал и обошелся без неё, найдя нужные параметры для stylesheet.css. Проблема полностью решена, хотя и не понятно почему она собственно возникла. Стиль ниже заставляет выглядеть элементы почти как раньше, если вдруг кому-то понадобится.

`QToolBar, QToolButton, QPushButton
{ 
  icon-size: 16px; /* maximum icon size */ 
}


QToolButton {
  padding: 1;
}

QTreeView::item
{
    height: 14px;
}

QComboBox {
    height: 22px;
    border: 1px;
    width: 30px;
}`
