### ISSUE TITLE
[bug] fcitx stop working on MyTetra v.1.42.2

### ISSUE THREAD

**Issue by dreamofi** [xintrea/mytetra_dev#68]
**Configuration:**
Linux mint 18.2 Sonya
MyTetra v.1.42.2

**Steps**

    Start MyTetra.
    Start typing, press CTR+SPACE to change input mode with fcitx

**Actual result**
 fcitx does not change input mode (e.g. for typing Japanese/Chinese etc.)

**Expected result**
 fcitx changes input mode (MyTetra v1.32.314 worked perfectly with fcitx)

**Comment by xintrea** [comment]
This is problem in Qt library. In MyTetra never blocking fcitx functional. Try compile standart QTextEdit sample in Qt 5.x.x and check fcitx functionality. After this, try compile MyTetra with this Qt library set.

**Comment by dreamofi** [comment]
Thank you, the problem was because I used a different version of Qt to compile MyTetra, which did not contain the fcitx plugin (libfcitxplatforminputcontextplugin.so) in "QTpath/plugin/platforminputcontexts/". After I switched back to the default Qt and recompiled Mytetra, everything is working as it should now.
