### ISSUE TITLE
[EXPIRED] Сбой диалога хранения настроек в русскоязычном каталоге

### ISSUE THREAD

**Issue by sergeevabc** [xintrea/mytetra_dev#69]
Win 7 x64, MyTetra 1.42.

Распаковываем содержание архива в русскоязычный каталог ```C:\Тетра``` и запускаем ```mytetra.exe```.

Видим диалог без выбора места хранения настроек (standart и portable).

![](https://images.vfl.ru/ii/1513264001/f3dfb1d4/19802385.png)

Переименовываем ```C:\Тетра``` в ```C:\Tetra``` и получаем ожидаемый диалог.

![](https://images.vfl.ru/ii/1513264001/cfb4b96f/19802386.png)

В эпоху Юникода запирать пользователя в англоязычном каталоге считаю моветоном.

P.S. Стандарт с буквой т на конце — в русском языке, а в английском — на конце d, т.е. Standard.

**Comment by sergeevabc** [comment]
Ау, есть кто живой?

**Comment by xintrea** [comment]
Да есть, есть. Просто заняты все. Временное решение - пользуйтесь портабельной установкой в англоязычном каталоге.

**Comment by sergeevabc** [comment]
Прошло два месяца, а дискриминация по языку и ныне там. Если же взглянуть шире: новые версии не выходили с 2016 года. Добавим сюда [хромающую орфографию][1] и получается неутешительная картина: не по Сеньке шапка. Закрываю вопрос как заброшенный. 

[1]: https://github.com/xintrea/mytetra_dev/commit/a56ca4032f9de35faddac728c46c73507a461ed4#diff-1db54208e2e6b0f6741f0361a4e81e59R395
