### ISSUE TITLE
Выбор лицензии - отправная точка проекта.

### ISSUE THREAD

**Issue by vovs03** [xintrea/mytetra_dev#72]
# License file

Множество проблем может быть вызвано от непонимания важности и необходимости продукта. В коммьюнити есть возможность заявить о своих правах на "код", "софт", "продукт", определив под какой лицензие оный будет распространяться в сети.

## Хорошо бы сделать:

- Сommunity profile > [Checklist](https://github.com/xintrea/mytetra_dev/community)
-  License  > [Choosing a license](https://help.github.com/articles/adding-a-license-to-a-repository/)

**Comment by xintrea** [comment]
Я ничего не понял. Кто кому в каком камьюните что должен заявить?

**Comment by ghost** [comment]
На сайте программы (ссылка в описании репозитория)  указана лицензия: GPL v.3.

**Comment by vovs03** [comment]
> На сайте программы (ссылка в описании репозитория) указана лицензия: GPL v.3.

@geo-v  А где конкретно в репозитории ледит файл с лицензией?
Ни в одной ветке такового не имеется ((

**Comment by xintrea** [comment]
В каталоге /app/src/ лежат два файла:

licenseBSD.txt
licenseGPL.txt
