### ISSUE TITLE
Kubuntu dark theme issues.

### ISSUE THREAD

**Issue by timoc** [xintrea/mytetra_dev#74]
some colors seem to be fixed and not theme driven. 
![screenshot_20180602_163604](https://user-images.githubusercontent.com/140698/40877564-4fd2e056-6683-11e8-9c33-452c414df2a3.png)

**Comment by xintrea** [comment]
Please drawing dark theme icons set, and i include this icons to application.

For other color setting try use Qt5 Configuration Tool: 

https://www.opendesktop.org/content/show.php/Qt5+Configuration+Tool?content=168066

**Comment by timoc** [comment]
Kubuntu is a KDE desktop, so QT colour settings are native tothe desktop. 
I will check out the next release. FWIW The issue is usually that the QT form hard codes the color information (such as black for fonts), so that when an inverse theme is chosen, the surrounding colours are changed, but the hard coded color does not.

**Comment by UUSR** [comment]
@timoc I am interested in this topic, which **stylesheet.css** did you use?

**Comment by timoc** [comment]
Whatever comes out of the box. i could not use it so reported it and moved on.
