### ISSUE TITLE
$(dirname $0) => $(dirname $(readlink -e $0))

### ISSUE THREAD

**Issue by batonio** [xintrea/mytetra_dev#75]
Строку 
`PROGDIR=$(dirname $0)`
файла
**mytetra.run**
имеет смысл заменить на 
`PROGDIR=$(dirname $(readlink -e $0))`
, так как при создании ссылки на на mytetra.run и запуск через неё приводит к "печальным" последствиям в виде запуска бесконечного количества экземпляров программы и зависанию ПК(по крайней мере, моего ПК под управлением Ubuntu 16.04)

P.S.
Прошу прощения что не создал pull request - grep по PROGDIR ничего даёт

**Comment by xintrea** [comment]
А с обычным файлом ( не линком) ваше решение правильно работает?

**Comment by xintrea** [comment]
Решено в коммите https://github.com/xintrea/mytetra_dev/commit/81929b8d1222b02784693069728d4e263accead5
