### ISSUE TITLE
Текст выглядит "тоньше" после bold/unbold

### ISSUE THREAD

**Issue by maximvl** [xintrea/mytetra_dev#76]
Сделал слово "under" жирным и потом обратно - оно стало выглядеть тоньше остального текста.

![](https://i.imgur.com/Bgto5aw.png)

**Comment by xintrea** [comment]
Обоженьки, действительно. Я бы сказал, неожиданно. Попозже посмотрю как так получается.

**Comment by xintrea** [comment]
Видимо, тут зависимость от разрешения экрана (HiDPI или что-то такое). На старых экранах этой проблемы не было, на новых имеем:

С Bold:
    `<span style=" font-weight:600;">строка</span>`

Без Bold:
    `<span style=" font-weight:0;">строка</span>`

А для всего текста: 
    `<body style=" font-family:'DejaVu Sans'; font-size:11pt; font-weight:400;`

Поэтому и становится тонким. Щас подумаю как исправить.

**Comment by xintrea** [comment]
Исправлено в коммите https://github.com/xintrea/mytetra_dev/commit/8ca52ded7f411a1a0cbfddd5ab6db1d4f82a9ba6

**Comment by xintrea** [comment]
Кстати, на ноутбуке с Windows такой проблемы нет.
