### ISSUE TITLE
Падение на Windows

### ISSUE THREAD

**Issue by tomintaiga** [xintrea/mytetra_dev#83]
При смене папки с базой (раньше была в другом месте), после перезапуска программы появляется такое окно:
![err](https://user-images.githubusercontent.com/26430678/45250900-92189500-b345-11e8-92d4-66558d170c57.png)
После его закрытия программа падает. 

Вывод лога при старте отладочной версии:
![log](https://user-images.githubusercontent.com/26430678/45250934-f6d3ef80-b345-11e8-82ba-d93dce3dad9a.png)

**Comment by xintrea** [comment]
Значит такого файла нет. В conf.ini пропишите правильный путь ручками,и все заработает. В новой версии будет открываться окно выбора файла базы если файл не найден.
