### ISSUE TITLE
В каком окружении и с какими зависимостями вы собираете проект?

### ISSUE THREAD

**Issue by lapkaway** [xintrea/mytetra_dev#84]
Под какими операционными системами?
Какой компилятор и версия?
Какая версия Qt?
Какие-то еще зависимости есть или планируются?

**Comment by xintrea** [comment]
Собираю под Debian Linux 64 bit Stable и Windows 7 PRO 32/64 bit. Энтузиасты собирают под другие линуксы, под FreeBSD, под MacOS, но версии опуерационок я не знаю.

Сейчас разработка идет на Qt 5.9.2 взятый с сайта qt.io. Какой там компилер в комплекте такой и компилит (на Дебиане сейчас gcc 6.3.0, но я даже не проверял используется дебиановский или тот что в составе Qt идет и идет ли таковой вообще под Linux). Никаких фишек из именно Qt 5.9.2 не используется.

Сторонних зависимостей нет, проект Qt-онли.
