### ISSUE TITLE
[bug] Не всегда корректно срабатывает форматирование выделенного(ых) абзаца(ев) стилем code

### ISSUE THREAD

**Issue by DikBSD** [xintrea/mytetra_dev#90]
**Система:**
Windows 7 x86_64.
**Версия:**
MyTetra v.1.44.46
**Проблема**
Если в абзаце (в html - просмотр и правка html кода) встречается что-то, вроде
`"<span style=" font-family:'MS Shell Dlg 2';"><br /></span>",`
то при форматировании этого абзаца инструментом Code ({}) абзац либо вообще не форматируется в Сову (визуально ничего не происходит), либо - "красится" в цвет для Code, но отступ не устанавливается.
Вот пример такого текста (проблема выделена [b]полужирным[/b]):

```
<p style=" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:'Courier New';">cd repo</span></p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:'Courier New';">git remote add upstream git://github.com/user/repo.git</span></p>
<p style=" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:'Courier New';">git fetch upstream</span><span style=" font-family:'MS Shell Dlg 2';"><br /></span></p>
```

Эти 3 абзаца, **вместе выделенные**, никак не форматируются. 
Первые 2 по одному форматируются корректно. 
А последний - форматируется шрифтом и цветом, **но не делается отступ**.

**Comment by xintrea** [comment]
Если включить отображение специальных символов, то переносы строк везде одинаковые? Они должны походить на букву Пи. Если перенос строк "мягкий", отображаемый как стрелка-кочерга, то на такой строке форматирование абзаца не будет полностью применяться. Потому что на мягком переносе абзац не считается абзацем, а считается продолжением строки.

Есть даже специальная клавиша преобразования мягких переносов в настоящие. Выделяете текст, нажимаете ее, переносы станут правильными.

У вас на последней строке мягкий перенос. Получается, что вы выделяете последнюю строчку не полностью (так как она заканчивается на самом деле на строчку ниже). Редактор видит, что выделение сделано не строго на границах абзацев (начало вы делаете, скорее всего, с границы, а конец получается что на середине строки). И поэтому не может применить форматирование абзаца.

**Comment by xintrea** [comment]
Not bug.

**Comment by DikBSD** [comment]
Понятно. Просто инструмент работает ожидаемо не всегда. Если бы была проверка на мягкие переносы и автоматически преобразовывались в настоящие в процессе форматирования в Code - было бы лучше.
