### ISSUE TITLE
при форматировании в Code слетает предыдущее форматирование

### ISSUE THREAD

**Issue by fftmp** [xintrea/mytetra_dev#94]
Если выделить текст, затем сделать его жирным/курсивом/подчёркнутым, а после этого отформатировать этот же фрагмент как код (ctrl+M), то жирный/курсив/подчёркивание слетают (а Code применяется).
Для сравнения, если производить действия в обратном порядке - сначала помечать как код, а затем делать текст жирным/курсивом/подчёркнутым, то применяются все атрибуты, т.е. например можно получить код, к-ый будет одновременно подчёркнутым.

Кстати, в код можно форматировать произвольные фрагменты строк, а в help-строке при наведении на Code написано: "Для форматирования в код необходимо целиком выделить абзац(ы)". Если это гарантированно рабочее поведение, то м.б. поправить help-строку.

v.1.44.31

**Comment by xintrea** [comment]
> Если выделить текст, затем сделать его жирным/курсивом/подчёркнутым, а после этого отформатировать этот же фрагмент как код (ctrl+M), то жирный/курсив/подчёркивание слетают (а Code применяется).

Да, так и должно быть. В 1.43 было точно такое же поведение.

> Кстати, в код можно форматировать произвольные фрагменты строк, а в help-строке при наведении на Code написано: "Для форматирования в код необходимо целиком выделить абзац(ы)". Если это гарантированно рабочее поведение, то м.б. поправить help-строку.

Тут имеется в виду, что для **полного** форматирования в код нужно выделять абзацы. Тогда будет и начертание как у кода, и форматирование с отступами как у кода. Если форматировать только чать строки, то применится только начертание.

**Comment by fftmp** [comment]
Да, в прошлой версии тоже так было. Кажется нелогичным, что итоговый стиль текста зависит от порядка применения эффектов. Но если Вы как автор считаете, что это правильное поведение, то задачу можно закрывать.
